baseURL = "https://valeriarojas.cl/"
languageCode = "es-CL"
locale = "es-CL"
title = "Valeria Rojas"
enableRobotsTXT = true
summaryLength = 24
disableKinds = ["taxonomy", "term"]

[params]
  description = "Empecé a aprender cerámica en 2024. En este sitio comparto un archivo personal de las piezas que he realizado desde entonces."
  images = ["/uploads/site/valeria-rojas-artista.jpeg"]

[permalinks]
  pieces = "/obras/:slug/"
  pages = "/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.4
