baseURL = "https://valeriarojas.cl/"
languageCode = "es-CL"
locale = "es-CL"
title = "Valeria Rojas"
enableRobotsTXT = true
summaryLength = 24
disableKinds = ["taxonomy", "term"]

[params]
  description = "Soy Valeria Rojas Mandiola. Este sitio reúne una selección de mis piezas y procesos en escultura cerámica."
  images = ["/uploads/site/valeria-rojas-artista.jpeg"]

[permalinks]
  pieces = "/piezas/:slug/"
  pages = "/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.4
